import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

final localeNotifier = ValueNotifier<String>('en');

class L {
  static String _lang = 'en';
  static String get lang => _lang;

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('app_language') ?? 'en';
    localeNotifier.value = _lang;
  }

  static Future<void> setLanguage(String code) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', code);
    _lang = code;
    localeNotifier.value = code;
  }

  static String tr(String key) {
    return _strings[_lang]?[key] ?? _strings['en']?[key] ?? key;
  }

  static const List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'name': 'English', 'nativeName': 'English', 'flag': '🇬🇧'},
    {'code': 'te', 'name': 'Telugu', 'nativeName': 'తెలుగు', 'flag': '🇮🇳'},
    {'code': 'hi', 'name': 'Hindi', 'nativeName': 'हिंदी', 'flag': '🇮🇳'},
    {'code': 'ta', 'name': 'Tamil', 'nativeName': 'தமிழ்', 'flag': '🇮🇳'},
    {'code': 'kn', 'name': 'Kannada', 'nativeName': 'ಕನ್ನಡ', 'flag': '🇮🇳'},
    {'code': 'ml', 'name': 'Malayalam', 'nativeName': 'മലയാളം', 'flag': '🇮🇳'},
  ];

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // Auth
      'welcome': 'Welcome to\\nJago 👋',
      'welcome_sub': 'Safe, affordable rides — anywhere',
      'enter_otp': 'Enter OTP\n📱',
      'otp_sent_to': 'OTP sent to +91 ',
      'mobile_number': 'Mobile Number',
      'get_otp': 'Get OTP →',
      'verify_continue': 'Verify & Continue →',
      'enter_6digit_otp': 'Enter 6-Digit OTP',
      'resend_in': 'Resend OTP in ',
      'back_to_phone': '← Back to Phone',
      'your_data_secure': 'Your data is secure & private',
      'quick_rides': 'Quick Rides',
      'verified_pilots': 'Verified Pilots',
      'easy_pay': 'Easy Pay',
      'invalid_otp': 'Invalid OTP. Try again.',
      'enter_valid_phone': 'Enter a valid 10-digit number',
      'dev_otp': 'Dev OTP: ',
      // Registration
      'complete_profile': 'Complete your\nProfile ✨',
      'complete_profile_sub': 'Just a few details to get started',
      'full_name': 'Full Name',
      'full_name_hint': 'Enter your full name',
      'email': 'Email (Optional)',
      'email_hint': 'your@email.com',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'other': 'Other',
      'save_continue': 'Save & Continue →',
      'enter_full_name': 'Please enter your full name',
      'reg_failed': 'Registration failed. Try again.',
      'network_error': 'Network error. Check connection.',
      // Home
      'where_to': 'Where to?',
      'search_destination': 'Search destination...',
      'book_ride': 'Book Ride',
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'quick_book': 'Quick Book',
      'recent_places': 'Recent Places',
      'no_recent': 'No recent places',
      // Profile
      'my_profile': 'My Profile',
      'edit_profile': 'Edit Profile',
      'save_profile': 'Save Profile',
      'cancel': 'Cancel',
      'wallet_balance': 'Wallet Balance',
      'loyalty_points': 'Loyalty Points',
      'total_rides': 'Total Rides',
      'total_spent': 'Total Spent',
      'account_settings': 'Account Settings',
      'saved_places': 'Saved Places',
      'ride_preferences': 'Ride Preferences',
      'monthly_pass': 'Monthly Pass',
      'my_coins': 'My Jago Coins',
      'safety_contacts': 'Safety & Emergency',
      'refer_earn': 'Refer & Earn',
      'support_chat': 'Support Chat',
      'language_settings': 'Language Settings',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System Default',
      'logout': 'Logout',
      'logout_confirm': 'Logout?',
      'logout_message': 'Are you sure you want to logout?',
      'yes_logout': 'Yes, Logout',
      'delete_account': 'Delete Account',
      'delete_confirm': 'Delete Account?',
      'deactivate': 'Deactivate Account',
      'deactivate_desc': 'Account will be hidden temporarily. Can be reactivated by logging in again.',
      'delete_permanent': 'Permanently Delete',
      'delete_desc': 'All data will be permanently removed. This action cannot be undone.',
      'profile_updated': 'Profile updated!',
      'update_failed': 'Update failed. Try again.',
      // Booking
      'select_ride': 'Select Ride',
      'pick_location': 'Pickup Location',
      'drop_location': 'Drop Location',
      'confirm_booking': 'Confirm Booking',
      'searching_pilot': 'Searching for Pilot...',
      'pilot_found': 'Pilot Found!',
      'ride_started': 'Ride Started',
      'ride_completed': 'Ride Completed',
      'rate_your_ride': 'Rate Your Ride',
      'book_for_someone': 'Book for Someone Else',
      'passenger_name': 'Passenger Name',
      'passenger_phone': 'Passenger Phone',
      'receiver_name': 'Receiver Name',
      'receiver_phone': 'Receiver Phone',
      'parcel_otp_info': 'Delivery OTP will be sent to receiver\'s phone',
      'estimated_fare': 'Estimated Fare',
      'distance': 'Distance',
      'duration': 'Duration',
      // General
      'ok': 'OK',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'submit': 'Submit',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'no_data': 'No data found',
      'choose_language': 'Choose Language',
      'language': 'Language',
      'select_language': 'Select Language',
      'app_language': 'App Language',
      'rupee': '₹',
      'km': 'km',
      'mins': 'mins',
      'enter_destination': 'Please enter a destination',
      'service_area': 'Hyderabad & Andhra Pradesh',
    },
    'te': {
      // Auth
      'welcome': 'Jago కి\nస్వాగతం 👋',
      'welcome_sub': 'సురక్షితమైన, చవకైన రైడ్లు — ఎక్కడైనా',
      'enter_otp': 'OTP నమోదు\nచేయండి 📱',
      'otp_sent_to': 'OTP పంపించబడింది +91 ',
      'mobile_number': 'మొబైల్ నంబర్',
      'get_otp': 'OTP పంపండి →',
      'verify_continue': 'Verify & Continue →',
      'enter_6digit_otp': '6-అంకెల OTP నమోదు చేయండి',
      'resend_in': 'OTP మళ్ళీ పంపండి ',
      'back_to_phone': '← నంబర్ మార్చండి',
      'your_data_secure': 'మీ డేటా సురక్షితంగా ఉంది',
      'quick_rides': 'వేగంగా రైడ్లు',
      'verified_pilots': 'ధృవీకరించిన పైలట్లు',
      'easy_pay': 'సులభ చెల్లింపు',
      'invalid_otp': 'తప్పు OTP. మళ్ళీ ప్రయత్నించండి.',
      'enter_valid_phone': 'చెల్లుబాటు అయ్యే 10-అంకెల నంబర్ నమోదు చేయండి',
      'dev_otp': 'Dev OTP: ',
      // Registration
      'complete_profile': 'మీ ప్రొఫైల్\nపూర్తి చేయండి ✨',
      'complete_profile_sub': 'ప్రారంభించడానికి కొన్ని వివరాలు',
      'full_name': 'పూర్తి పేరు',
      'full_name_hint': 'మీ పూర్తి పేరు నమోదు చేయండి',
      'email': 'ఇమెయిల్ (ఐచ్ఛికం)',
      'email_hint': 'your@email.com',
      'gender': 'లింగం',
      'male': 'పురుషుడు',
      'female': 'స్త్రీ',
      'other': 'ఇతర',
      'save_continue': 'సేవ్ & కొనసాగించండి →',
      'enter_full_name': 'మీ పూర్తి పేరు నమోదు చేయండి',
      'reg_failed': 'నమోదు విఫలమైంది. మళ్ళీ ప్రయత్నించండి.',
      'network_error': 'నెట్వర్క్ లోపం. కనెక్షన్ తనిఖీ చేయండి.',
      // Home
      'where_to': 'ఎక్కడికి వెళ్ళాలి?',
      'search_destination': 'గమ్యస్థానం శోధించండి...',
      'book_ride': 'రైడ్ బుక్ చేయండి',
      'good_morning': 'శుభోదయం',
      'good_afternoon': 'శుభ మధ్యాహ్నం',
      'good_evening': 'శుభ సాయంత్రం',
      'quick_book': 'త్వరిత బుకింగ్',
      'recent_places': 'ఇటీవలి స్థలాలు',
      'no_recent': 'ఇటీవలి స్థలాలు లేవు',
      // Profile
      'my_profile': 'నా ప్రొఫైల్',
      'edit_profile': 'ప్రొఫైల్ సవరించండి',
      'save_profile': 'ప్రొఫైల్ సేవ్ చేయండి',
      'cancel': 'రద్దు చేయండి',
      'wallet_balance': 'వాలెట్ బ్యాలెన్స్',
      'loyalty_points': 'లాయల్టీ పాయింట్లు',
      'total_rides': 'మొత్తం రైడ్లు',
      'total_spent': 'మొత్తం ఖర్చు',
      'account_settings': 'ఖాతా సెట్టింగ్లు',
      'saved_places': 'సేవ్ చేసిన స్థలాలు',
      'ride_preferences': 'రైడ్ ప్రాధాన్యతలు',
      'monthly_pass': 'నెలవారీ పాస్',
      'my_coins': 'నా Jago కాయిన్లు',
      'safety_contacts': 'సురక్షత & అత్యవసర',
      'refer_earn': 'రెఫర్ & సంపాదించండి',
      'support_chat': 'మద్దతు చాట్',
      'language_settings': 'భాషా సెట్టింగ్లు',
      'theme': 'థీమ్',
      'light': 'లైట్',
      'dark': 'డార్క్',
      'system': 'సిస్టమ్ డిఫాల్ట్',
      'logout': 'లాగ్అవుట్',
      'logout_confirm': 'లాగ్అవుట్ చేయాలా?',
      'logout_message': 'మీరు ఖచ్చితంగా లాగ్అవుట్ చేయాలనుకుంటున్నారా?',
      'yes_logout': 'అవును, లాగ్అవుట్',
      'delete_account': 'ఖాతా తొలగించండి',
      'delete_confirm': 'ఖాతా తొలగించాలా?',
      'deactivate': 'ఖాతా నిష్క్రియం చేయండి',
      'deactivate_desc': 'ఖాతా తాత్కాలికంగా దాచబడుతుంది. మళ్ళీ లాగిన్ చేయడం ద్వారా పున:స్థాపించవచ్చు.',
      'delete_permanent': 'శాశ్వతంగా తొలగించండి',
      'delete_desc': 'మీ అన్ని డేటా శాశ్వతంగా తొలగించబడుతుంది. ఈ చర్యను రద్దు చేయలేరు.',
      'profile_updated': 'ప్రొఫైల్ అప్‌డేట్ చేయబడింది!',
      'update_failed': 'అప్‌డేట్ విఫలమైంది. మళ్ళీ ప్రయత్నించండి.',
      // Booking
      'select_ride': 'రైడ్ ఎంచుకోండి',
      'pick_location': 'పికప్ స్థానం',
      'drop_location': 'డ్రాప్ స్థానం',
      'confirm_booking': 'బుకింగ్ నిర్ధారించండి',
      'searching_pilot': 'పైలట్ కోసం శోధిస్తోంది...',
      'pilot_found': 'పైలట్ దొరికాడు!',
      'ride_started': 'రైడ్ ప్రారంభమైంది',
      'ride_completed': 'రైడ్ పూర్తైంది',
      'rate_your_ride': 'మీ రైడ్ రేట్ చేయండి',
      'book_for_someone': 'వేరొకరి కోసం బుక్ చేయండి',
      'passenger_name': 'ప్రయాణికుడి పేరు',
      'passenger_phone': 'ప్రయాణికుడి ఫోన్',
      'receiver_name': 'స్వీకర్త పేరు',
      'receiver_phone': 'స్వీకర్త ఫోన్',
      'parcel_otp_info': 'డెలివరీ OTP స్వీకర్త ఫోన్‌కు పంపబడుతుంది',
      'estimated_fare': 'అంచనా ఛార్జీ',
      'distance': 'దూరం',
      'duration': 'సమయం',
      // General
      'ok': 'సరే',
      'yes': 'అవును',
      'no': 'కాదు',
      'close': 'మూసివేయండి',
      'submit': 'సమర్పించండి',
      'loading': 'లోడ్ అవుతోంది...',
      'error': 'లోపం',
      'success': 'విజయవంతం',
      'retry': 'మళ్ళీ ప్రయత్నించండి',
      'no_data': 'డేటా కనుగొనబడలేదు',
      'choose_language': 'భాష ఎంచుకోండి',
      'language': 'భాష',
      'select_language': 'భాష ఎంచుకోండి',
      'app_language': 'యాప్ భాష',
      'rupee': '₹',
      'km': 'కి.మీ',
      'mins': 'నిమిషాలు',
      'enter_destination': 'గమ్యస్థానం నమోదు చేయండి',
      'service_area': 'హైదరాబాద్ & ఆంధ్రప్రదేశ్',
    },
    'hi': {
      // Auth
      'welcome': 'Jago में\nस्वागत है 👋',
      'welcome_sub': 'सुरक्षित, किफायती सवारी — कहीं भी',
      'enter_otp': 'OTP दर्ज\nकरें 📱',
      'otp_sent_to': 'OTP भेजा गया +91 ',
      'mobile_number': 'मोबाइल नंबर',
      'get_otp': 'OTP पाएं →',
      'verify_continue': 'Verify & Continue →',
      'enter_6digit_otp': '6-अंकों का OTP दर्ज करें',
      'resend_in': 'OTP पुनः भेजें ',
      'back_to_phone': '← नंबर बदलें',
      'your_data_secure': 'आपका डेटा सुरक्षित है',
      'quick_rides': 'त्वरित सवारी',
      'verified_pilots': 'सत्यापित पायलट',
      'easy_pay': 'आसान भुगतान',
      'invalid_otp': 'गलत OTP। फिर प्रयास करें।',
      'enter_valid_phone': 'वैध 10 अंकों का नंबर दर्ज करें',
      'dev_otp': 'Dev OTP: ',
      // Registration
      'complete_profile': 'अपनी\nप्रोफ़ाइल पूरी करें ✨',
      'complete_profile_sub': 'शुरू करने के लिए कुछ विवरण',
      'full_name': 'पूरा नाम',
      'full_name_hint': 'अपना पूरा नाम दर्ज करें',
      'email': 'ईमेल (वैकल्पिक)',
      'email_hint': 'your@email.com',
      'gender': 'लिंग',
      'male': 'पुरुष',
      'female': 'महिला',
      'other': 'अन्य',
      'save_continue': 'सहेजें & जारी रखें →',
      'enter_full_name': 'कृपया अपना पूरा नाम दर्ज करें',
      'reg_failed': 'पंजीकरण विफल। फिर प्रयास करें।',
      'network_error': 'नेटवर्क त्रुटि। कनेक्शन जांचें।',
      // Home
      'where_to': 'कहाँ जाना है?',
      'search_destination': 'गंतव्य खोजें...',
      'book_ride': 'सवारी बुक करें',
      'good_morning': 'सुप्रभात',
      'good_afternoon': 'शुभ दोपहर',
      'good_evening': 'शुभ संध्या',
      'quick_book': 'त्वरित बुकिंग',
      'recent_places': 'हाल के स्थान',
      'no_recent': 'कोई हाल के स्थान नहीं',
      // Profile
      'my_profile': 'मेरी प्रोफ़ाइल',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'save_profile': 'प्रोफ़ाइल सहेजें',
      'cancel': 'रद्द करें',
      'wallet_balance': 'वॉलेट बैलेंस',
      'loyalty_points': 'लॉयल्टी पॉइंट्स',
      'total_rides': 'कुल सवारी',
      'total_spent': 'कुल खर्च',
      'account_settings': 'खाता सेटिंग',
      'saved_places': 'सहेजे गए स्थान',
      'ride_preferences': 'सवारी प्राथमिकताएं',
      'monthly_pass': 'मासिक पास',
      'my_coins': 'मेरे Jago सिक्के',
      'safety_contacts': 'सुरक्षा और आपातकाल',
      'refer_earn': 'रेफर करें & कमाएं',
      'support_chat': 'सहायता चैट',
      'language_settings': 'भाषा सेटिंग',
      'theme': 'थीम',
      'light': 'हल्का',
      'dark': 'गहरा',
      'system': 'सिस्टम डिफ़ॉल्ट',
      'logout': 'लॉगआउट',
      'logout_confirm': 'लॉगआउट करें?',
      'logout_message': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'yes_logout': 'हाँ, लॉगआउट',
      'delete_account': 'खाता हटाएं',
      'delete_confirm': 'खाता हटाएं?',
      'deactivate': 'खाता निष्क्रिय करें',
      'deactivate_desc': 'खाता अस्थायी रूप से छिपाया जाएगा। फिर से लॉगिन करके पुनः सक्रिय किया जा सकता है।',
      'delete_permanent': 'स्थायी रूप से हटाएं',
      'delete_desc': 'सभी डेटा स्थायी रूप से हटा दिया जाएगा। यह क्रिया वापस नहीं की जा सकती।',
      'profile_updated': 'प्रोफ़ाइल अपडेट हो गई!',
      'update_failed': 'अपडेट विफल। फिर प्रयास करें।',
      // Booking
      'select_ride': 'सवारी चुनें',
      'pick_location': 'पिकअप स्थान',
      'drop_location': 'ड्रॉप स्थान',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'searching_pilot': 'पायलट खोज रहे हैं...',
      'pilot_found': 'पायलट मिल गया!',
      'ride_started': 'सवारी शुरू हुई',
      'ride_completed': 'सवारी पूरी हुई',
      'rate_your_ride': 'अपनी सवारी रेट करें',
      'book_for_someone': 'किसी और के लिए बुक करें',
      'passenger_name': 'यात्री का नाम',
      'passenger_phone': 'यात्री का फोन',
      'receiver_name': 'प्राप्तकर्ता का नाम',
      'receiver_phone': 'प्राप्तकर्ता का फोन',
      'parcel_otp_info': 'डिलीवरी OTP प्राप्तकर्ता के फोन पर भेजा जाएगा',
      'estimated_fare': 'अनुमानित किराया',
      'distance': 'दूरी',
      'duration': 'समय',
      // General
      'ok': 'ठीक है',
      'yes': 'हाँ',
      'no': 'नहीं',
      'close': 'बंद करें',
      'submit': 'जमा करें',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',
      'retry': 'पुनः प्रयास करें',
      'no_data': 'कोई डेटा नहीं मिला',
      'choose_language': 'भाषा चुनें',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'app_language': 'ऐप भाषा',
      'rupee': '₹',
      'km': 'किमी',
      'mins': 'मिनट',
      'enter_destination': 'गंतव्य दर्ज करें',
      'service_area': 'हैदराबाद और आंध्र प्रदेश',
    },
    'ta': {
      'welcome': 'Jago-க்கு\nவரவேற்கிறோம் 👋',
      'welcome_sub': 'பாதுகாப்பான, மலிவான சவாரிகள் — எங்கும்',
      'enter_otp': 'OTP உள்ளிடவும் 📱',
      'otp_sent_to': 'OTP அனுப்பப்பட்டது +91 ',
      'mobile_number': 'மொபைல் எண்',
      'get_otp': 'OTP பெறவும் →',
      'verify_continue': 'Verify & Continue →',
      'enter_6digit_otp': '6 இலக்க OTP உள்ளிடவும்',
      'resend_in': 'OTP மீண்டும் அனுப்பவும் ',
      'back_to_phone': '← திரும்பு',
      'your_data_secure': 'உங்கள் தரவு பாதுகாப்பாக உள்ளது',
      'quick_rides': 'விரைவு சவாரிகள்',
      'verified_pilots': 'சரிபார்க்கப்பட்ட பைலட்கள்',
      'easy_pay': 'எளிய கட்டணம்',
      'invalid_otp': 'தவறான OTP. மீண்டும் முயற்சிக்கவும்.',
      'enter_valid_phone': 'சரியான 10 இலக்க எண் உள்ளிடவும்',
      'dev_otp': 'Dev OTP: ',
      'complete_profile': 'உங்கள் சுயவிவரத்தை\nபூர்த்தி செய்யுங்கள் ✨',
      'complete_profile_sub': 'சில விவரங்கள் தேவை',
      'full_name': 'முழு பெயர்',
      'full_name_hint': 'உங்கள் முழு பெயரை உள்ளிடவும்',
      'email': 'மின்னஞ்சல் (விரும்பினால்)',
      'email_hint': 'your@email.com',
      'gender': 'பாலினம்',
      'male': 'ஆண்',
      'female': 'பெண்',
      'other': 'மற்றவை',
      'save_continue': 'சேமிக்கவும் & தொடரவும் →',
      'enter_full_name': 'உங்கள் முழு பெயரை உள்ளிடவும்',
      'reg_failed': 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
      'network_error': 'நெட்வொர்க் பிழை. இணைப்பை சரிபார்க்கவும்.',
      'where_to': 'எங்கே செல்ல வேண்டும்?',
      'search_destination': 'இலக்கை தேடவும்...',
      'book_ride': 'சவாரி பதிவு செய்யுங்கள்',
      'good_morning': 'காலை வணக்கம்',
      'good_afternoon': 'மதிய வணக்கம்',
      'good_evening': 'மாலை வணக்கம்',
      'quick_book': 'விரைவு பதிவு',
      'recent_places': 'சமீபத்திய இடங்கள்',
      'no_recent': 'சமீபத்திய இடங்கள் இல்லை',
      'my_profile': 'என் சுயவிவரம்',
      'edit_profile': 'சுயவிவரத்தை திருத்தவும்',
      'save_profile': 'சுயவிவரத்தை சேமிக்கவும்',
      'cancel': 'ரத்து செய்யவும்',
      'wallet_balance': 'வாலட் இருப்பு',
      'loyalty_points': 'விசுவாச புள்ளிகள்',
      'total_rides': 'மொத்த சவாரிகள்',
      'total_spent': 'மொத்த செலவு',
      'account_settings': 'கணக்கு அமைப்புகள்',
      'saved_places': 'சேமிக்கப்பட்ட இடங்கள்',
      'ride_preferences': 'சவாரி விருப்பங்கள்',
      'monthly_pass': 'மாதாந்திர பாஸ்',
      'my_coins': 'என் Jago நாணயங்கள்',
      'safety_contacts': 'பாதுகாப்பு & அவசரநிலை',
      'refer_earn': 'பரிந்துரை & சம்பாதி',
      'support_chat': 'ஆதரவு அரட்டை',
      'language_settings': 'மொழி அமைப்புகள்',
      'theme': 'தீம்',
      'light': 'வெளிச்சமான',
      'dark': 'இருண்ட',
      'system': 'கணினி இயல்புநிலை',
      'logout': 'வெளியேறவும்',
      'logout_confirm': 'வெளியேற வேண்டுமா?',
      'logout_message': 'நீங்கள் உறுதியாக வெளியேற விரும்புகிறீர்களா?',
      'yes_logout': 'ஆம், வெளியேறவும்',
      'delete_account': 'கணக்கை நீக்கவும்',
      'delete_confirm': 'கணக்கை நீக்கவும்?',
      'deactivate': 'கணக்கை செயலிழக்கச் செய்யவும்',
      'deactivate_desc': 'கணக்கு தற்காலிகமாக மறைக்கப்படும்.',
      'delete_permanent': 'நிரந்தரமாக நீக்கவும்',
      'delete_desc': 'அனைத்து தரவும் நிரந்தரமாக நீக்கப்படும்.',
      'profile_updated': 'சுயவிவரம் புதுப்பிக்கப்பட்டது!',
      'update_failed': 'புதுப்பிப்பு தோல்வியடைந்தது.',
      'select_ride': 'சவாரி தேர்ந்தெடுக்கவும்',
      'pick_location': 'எடுக்கும் இடம்',
      'drop_location': 'இறக்கும் இடம்',
      'confirm_booking': 'பதிவை உறுதிப்படுத்தவும்',
      'searching_pilot': 'பைலட்டை தேடுகிறோம்...',
      'pilot_found': 'பைலட் கிடைத்தார்!',
      'ride_started': 'சவாரி தொடங்கியது',
      'ride_completed': 'சவாரி முடிந்தது',
      'rate_your_ride': 'உங்கள் சவாரியை மதிப்பிடவும்',
      'book_for_someone': 'வேறொருவருக்காக பதிவு செய்யவும்',
      'passenger_name': 'பயணியின் பெயர்',
      'passenger_phone': 'பயணியின் தொலைபேசி',
      'receiver_name': 'பெறுநரின் பெயர்',
      'receiver_phone': 'பெறுநரின் தொலைபேசி',
      'parcel_otp_info': 'டெலிவரி OTP பெறுநரின் தொலைபேசிக்கு அனுப்பப்படும்',
      'estimated_fare': 'மதிப்பிடப்பட்ட கட்டணம்',
      'distance': 'தூரம்',
      'duration': 'நேரம்',
      'ok': 'சரி',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'close': 'மூடவும்',
      'submit': 'சமர்ப்பிக்கவும்',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      'no_data': 'தரவு இல்லை',
      'choose_language': 'மொழியை தேர்ந்தெடுக்கவும்',
      'language': 'மொழி',
      'select_language': 'மொழியை தேர்ந்தெடுக்கவும்',
      'app_language': 'ஆப் மொழி',
      'rupee': '₹',
      'km': 'கி.மீ',
      'mins': 'நிமிடங்கள்',
      'enter_destination': 'இலக்கை உள்ளிடவும்',
      'service_area': 'ஹைதராபாத் & ஆந்திர பிரதேசம்',
    },
    'kn': {
      'welcome': 'Jago ಗೆ\nಸ್ವಾಗತ 👋',
      'welcome_sub': 'ಸುರಕ್ಷಿತ, ಕಡಿಮೆ ಬೆಲೆಯ ರೈಡ್‌ಗಳು — ಎಲ್ಲಿಯಾದರೂ',
      'enter_otp': 'OTP ನಮೂದಿಸಿ 📱',
      'otp_sent_to': 'OTP ಕಳಿಸಲಾಗಿದೆ +91 ',
      'mobile_number': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
      'get_otp': 'OTP ಪಡೆಯಿರಿ →',
      'verify_continue': 'Verify & Continue →',
      'enter_6digit_otp': '6-ಅಂಕಿ OTP ನಮೂದಿಸಿ',
      'resend_in': 'OTP ಮರುಕಳಿಸಿ ',
      'back_to_phone': '← ಹಿಂತಿರುಗಿ',
      'your_data_secure': 'ನಿಮ್ಮ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿದೆ',
      'quick_rides': 'ತ್ವರಿತ ರೈಡ್‌ಗಳು',
      'verified_pilots': 'ಪರಿಶೀಲಿಸಿದ ಪೈಲಟ್‌ಗಳು',
      'easy_pay': 'ಸುಲಭ ಪಾವತಿ',
      'invalid_otp': 'ತಪ್ಪಾದ OTP. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      'enter_valid_phone': 'ಸರಿಯಾದ 10-ಅಂಕಿ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
      'dev_otp': 'Dev OTP: ',
      'complete_profile': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್\nಪೂರ್ಣಗೊಳಿಸಿ ✨',
      'complete_profile_sub': 'ಕೆಲವು ವಿವರಗಳು ಬೇಕು',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'full_name_hint': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
      'email': 'ಇಮೇಲ್ (ಐಚ್ಛಿಕ)',
      'email_hint': 'your@email.com',
      'gender': 'ಲಿಂಗ',
      'male': 'ಪುರುಷ',
      'female': 'ಮಹಿಳೆ',
      'other': 'ಇತರರು',
      'save_continue': 'ಉಳಿಸಿ & ಮುಂದುವರಿಸಿ →',
      'enter_full_name': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
      'reg_failed': 'ನೋಂದಣಿ ವಿಫಲವಾಯಿತು.',
      'network_error': 'ನೆಟ್‌ವರ್ಕ್ ದೋಷ. ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ.',
      'where_to': 'ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?',
      'search_destination': 'ಗಮ್ಯಸ್ಥಾನ ಹುಡುಕಿ...',
      'book_ride': 'ರೈಡ್ ಬುಕ್ ಮಾಡಿ',
      'good_morning': 'ಶುಭೋದಯ',
      'good_afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
      'good_evening': 'ಶುಭ ಸಂಜೆ',
      'quick_book': 'ತ್ವರಿತ ಬುಕಿಂಗ್',
      'recent_places': 'ಇತ್ತೀಚಿನ ಸ್ಥಳಗಳು',
      'no_recent': 'ಇತ್ತೀಚಿನ ಸ್ಥಳಗಳಿಲ್ಲ',
      'my_profile': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'save_profile': 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'wallet_balance': 'ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್',
      'loyalty_points': 'ಲಾಯಲ್ಟಿ ಪಾಯಿಂಟ್‌ಗಳು',
      'total_rides': 'ಒಟ್ಟು ರೈಡ್‌ಗಳು',
      'total_spent': 'ಒಟ್ಟು ಖರ್ಚು',
      'account_settings': 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'saved_places': 'ಉಳಿಸಿದ ಸ್ಥಳಗಳು',
      'ride_preferences': 'ರೈಡ್ ಆದ್ಯತೆಗಳು',
      'monthly_pass': 'ಮಾಸಿಕ ಪಾಸ್',
      'my_coins': 'ನನ್ನ Jago ನಾಣ್ಯಗಳು',
      'safety_contacts': 'ಸುರಕ್ಷತೆ & ತುರ್ತು',
      'refer_earn': 'ರೆಫರ್ ಮಾಡಿ & ಗಳಿಸಿ',
      'support_chat': 'ಬೆಂಬಲ ಚಾಟ್',
      'language_settings': 'ಭಾಷಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'theme': 'ಥೀಮ್',
      'light': 'ಬೆಳಕು',
      'dark': 'ಗಾಢ',
      'system': 'ಸಿಸ್ಟಮ್ ಡಿಫಾಲ್ಟ್',
      'logout': 'ಲಾಗ್‌ಔಟ್',
      'logout_confirm': 'ಲಾಗ್‌ಔಟ್ ಮಾಡಲೇ?',
      'logout_message': 'ನೀವು ಖಚಿತವಾಗಿ ಲಾಗ್‌ಔಟ್ ಮಾಡಲು ಬಯಸುತ್ತೀರಾ?',
      'yes_logout': 'ಹೌದು, ಲಾಗ್‌ಔಟ್',
      'delete_account': 'ಖಾತೆ ಅಳಿಸಿ',
      'delete_confirm': 'ಖಾತೆ ಅಳಿಸಲೇ?',
      'deactivate': 'ಖಾತೆ ನಿಷ್ಕ್ರಿಯಗೊಳಿಸಿ',
      'deactivate_desc': 'ಖಾತೆ ತಾತ್ಕಾಲಿಕವಾಗಿ ಮರೆಮಾಡಲಾಗುತ್ತದೆ.',
      'delete_permanent': 'ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
      'delete_desc': 'ಎಲ್ಲಾ ಡೇಟಾ ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲಾಗುತ್ತದೆ.',
      'profile_updated': 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ!',
      'update_failed': 'ನವೀಕರಣ ವಿಫಲವಾಯಿತು.',
      'select_ride': 'ರೈಡ್ ಆಯ್ಕೆಮಾಡಿ',
      'pick_location': 'ಪಿಕಪ್ ಸ್ಥಳ',
      'drop_location': 'ಡ್ರಾಪ್ ಸ್ಥಳ',
      'confirm_booking': 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
      'searching_pilot': 'ಪೈಲಟ್ ಹುಡುಕುತ್ತಿದ್ದೇವೆ...',
      'pilot_found': 'ಪೈಲಟ್ ಸಿಕ್ಕಿದ!',
      'ride_started': 'ರೈಡ್ ಪ್ರಾರಂಭವಾಯಿತು',
      'ride_completed': 'ರೈಡ್ ಮುಗಿಯಿತು',
      'rate_your_ride': 'ನಿಮ್ಮ ರೈಡ್ ರೇಟ್ ಮಾಡಿ',
      'book_for_someone': 'ಇನ್ನೊಬ್ಬರಿಗಾಗಿ ಬುಕ್ ಮಾಡಿ',
      'passenger_name': 'ಪ್ರಯಾಣಿಕರ ಹೆಸರು',
      'passenger_phone': 'ಪ್ರಯಾಣಿಕರ ಫೋನ್',
      'receiver_name': 'ಸ್ವೀಕರಿಸುವವರ ಹೆಸರು',
      'receiver_phone': 'ಸ್ವೀಕರಿಸುವವರ ಫೋನ್',
      'parcel_otp_info': 'ಡೆಲಿವರಿ OTP ಸ್ವೀಕರಿಸುವವರ ಫೋನ್‌ಗೆ ಕಳಿಸಲಾಗುತ್ತದೆ',
      'estimated_fare': 'ಅಂದಾಜು ಶುಲ್ಕ',
      'distance': 'ದೂರ',
      'duration': 'ಸಮಯ',
      'ok': 'ಸರಿ',
      'yes': 'ಹೌದು',
      'no': 'ಇಲ್ಲ',
      'close': 'ಮುಚ್ಚಿ',
      'submit': 'ಸಲ್ಲಿಸಿ',
      'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      'error': 'ದೋಷ',
      'success': 'ಯಶಸ್ಸು',
      'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
      'no_data': 'ಡೇಟಾ ಇಲ್ಲ',
      'choose_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'language': 'ಭಾಷೆ',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'app_language': 'ಅಪ್ಲಿಕೇಶನ್ ಭಾಷೆ',
      'rupee': '₹',
      'km': 'ಕಿ.ಮೀ',
      'mins': 'ನಿಮಿಷಗಳು',
      'enter_destination': 'ಗಮ್ಯಸ್ಥಾನ ನಮೂದಿಸಿ',
      'service_area': 'ಹೈದರಾಬಾದ್ & ಆಂಧ್ರಪ್ರದೇಶ',
    },
    'ml': {
      'welcome': 'Jago-ലേക്ക്\nസ്വാഗതം 👋',
      'welcome_sub': 'സുരക്ഷിതമായ, താങ്ങാനാവുന്ന യാത്രകൾ — എവിടെയും',
      'enter_otp': 'OTP നൽകൂ 📱',
      'otp_sent_to': 'OTP അയച്ചു +91 ',
      'mobile_number': 'മൊബൈൽ നമ്പർ',
      'get_otp': 'OTP നേടൂ →',
      'verify_continue': 'Verify & Continue →',
      'enter_6digit_otp': '6 അക്ക OTP നൽകൂ',
      'resend_in': 'OTP വീണ്ടും അയക്കൂ ',
      'back_to_phone': '← തിരിച്ചു പോകൂ',
      'your_data_secure': 'നിങ്ങളുടെ ഡേറ്റ സുരക്ഷിതമാണ്',
      'quick_rides': 'വേഗത്തിലുള്ള യാത്രകൾ',
      'verified_pilots': 'സ്ഥിരീകരിച്ച പൈലറ്റ്സ്',
      'easy_pay': 'എളുപ്പ പേയ്‌മെന്റ്',
      'invalid_otp': 'തെറ്റായ OTP. വീണ്ടും ശ്രമിക്കൂ.',
      'enter_valid_phone': 'സാധുവായ 10 അക്ക നമ്പർ നൽകൂ',
      'dev_otp': 'Dev OTP: ',
      'complete_profile': 'നിങ്ങളുടെ\nപ്രൊഫൈൽ പൂർത്തിയാക്കൂ ✨',
      'complete_profile_sub': 'ചില വിവരങ്ങൾ ആവശ്യമാണ്',
      'full_name': 'പൂർണ്ണ നാമം',
      'full_name_hint': 'നിങ്ങളുടെ പൂർണ്ണ നാമം നൽകൂ',
      'email': 'ഇമെയിൽ (ഐച്ഛികം)',
      'email_hint': 'your@email.com',
      'gender': 'ലിംഗം',
      'male': 'പുരുഷൻ',
      'female': 'സ്ത്രീ',
      'other': 'മറ്റുള്ളവ',
      'save_continue': 'സേവ് ചെയ്ത് തുടരൂ →',
      'enter_full_name': 'ദയവായി നിങ്ങളുടെ പൂർണ്ണ നാമം നൽകൂ',
      'reg_failed': 'രജിസ്ട്രേഷൻ പരാജയപ്പെട്ടു.',
      'network_error': 'നെറ്റ്‌വർക്ക് പിശക്. കണക്ഷൻ പരിശോധിക്കൂ.',
      'where_to': 'എവിടേക്ക് പോകണം?',
      'search_destination': 'ലക്ഷ്യസ്ഥാനം തിരയൂ...',
      'book_ride': 'യാത്ര ബുക്ക് ചെയ്യൂ',
      'good_morning': 'സുപ്രഭാതം',
      'good_afternoon': 'ശുഭ ഉച്ചവേള',
      'good_evening': 'ശുഭ സന്ധ്യ',
      'quick_book': 'വേഗ ബുക്കിംഗ്',
      'recent_places': 'സമീപകാല സ്ഥലങ്ങൾ',
      'no_recent': 'സമീപകാല സ്ഥലങ്ങളൊന്നുമില്ല',
      'my_profile': 'എന്റെ പ്രൊഫൈൽ',
      'edit_profile': 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യൂ',
      'save_profile': 'പ്രൊഫൈൽ സേവ് ചെയ്യൂ',
      'cancel': 'റദ്ദാക്കൂ',
      'wallet_balance': 'വാലറ്റ് ബാലൻസ്',
      'loyalty_points': 'ലോയൽറ്റി പോയിന്റ്സ്',
      'total_rides': 'ആകെ യാത്രകൾ',
      'total_spent': 'ആകെ ചിലവ്',
      'account_settings': 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
      'saved_places': 'സേവ് ചെയ്ത സ്ഥലങ്ങൾ',
      'ride_preferences': 'യാത്ര മുൻഗണനകൾ',
      'monthly_pass': 'മാസ പാസ്',
      'my_coins': 'എന്റെ Jago നാണയങ്ങൾ',
      'safety_contacts': 'സുരക്ഷ & അടിയന്തരം',
      'refer_earn': 'റഫർ ചെയ്ത് നേടൂ',
      'support_chat': 'സഹായ ചാറ്റ്',
      'language_settings': 'ഭാഷ ക്രമീകരണങ്ങൾ',
      'theme': 'തീം',
      'light': 'ലൈറ്റ്',
      'dark': 'ഡാർക്ക്',
      'system': 'സിസ്റ്റം ഡിഫോൾട്ട്',
      'logout': 'ലോഗ്ഔട്ട്',
      'logout_confirm': 'ലോഗ്ഔട്ട് ചെയ്യണോ?',
      'logout_message': 'നിങ്ങൾ ഉറപ്പായും ലോഗ്ഔട്ട് ചെയ്യണോ?',
      'yes_logout': 'അതെ, ലോഗ്ഔട്ട്',
      'delete_account': 'അക്കൗണ്ട് ഇല്ലാതാക്കൂ',
      'delete_confirm': 'അക്കൗണ്ട് ഇല്ലാതാക്കണോ?',
      'deactivate': 'അക്കൗണ്ട് നിഷ്ക്രിയമാക്കൂ',
      'deactivate_desc': 'അക്കൗണ്ട് താൽക്കാലികമായി മറയ്ക്കും.',
      'delete_permanent': 'ശാശ്വതമായി ഇല്ലാതാക്കൂ',
      'delete_desc': 'എല്ലാ ഡേറ്റയും ശാശ്വതമായി ഇല്ലാതാകും.',
      'profile_updated': 'പ്രൊഫൈൽ അപ്ഡേറ്റ് ചെയ്തു!',
      'update_failed': 'അപ്ഡേറ്റ് പരാജയപ്പെട്ടു.',
      'select_ride': 'യാത്ര തിരഞ്ഞെടുക്കൂ',
      'pick_location': 'പിക്കപ്പ് സ്ഥലം',
      'drop_location': 'ഡ്രോപ്പ് സ്ഥലം',
      'confirm_booking': 'ബുക്കിംഗ് സ്ഥിരീകരിക്കൂ',
      'searching_pilot': 'പൈലറ്റ് തിരയുന്നു...',
      'pilot_found': 'പൈലറ്റ് കിട്ടി!',
      'ride_started': 'യാത്ര ആരംഭിച്ചു',
      'ride_completed': 'യാത്ര പൂർത്തിയായി',
      'rate_your_ride': 'നിങ്ങളുടെ യാത്ര റേറ്റ് ചെയ്യൂ',
      'book_for_someone': 'മറ്റൊരാൾക്കായി ബുക്ക് ചെയ്യൂ',
      'passenger_name': 'യാത്രക്കാരന്റെ പേര്',
      'passenger_phone': 'യാത്രക്കാരന്റെ ഫോൺ',
      'receiver_name': 'സ്വീകർത്താവിന്റെ പേര്',
      'receiver_phone': 'സ്വീകർത്താവിന്റെ ഫോൺ',
      'parcel_otp_info': 'ഡെലിവറി OTP സ്വീകർത്താവിന്റെ ഫോണിൽ അയക്കും',
      'estimated_fare': 'ഏകദേശ ചാർജ്',
      'distance': 'ദൂരം',
      'duration': 'സമയം',
      'ok': 'ശരി',
      'yes': 'അതെ',
      'no': 'ഇല്ല',
      'close': 'അടക്കൂ',
      'submit': 'സമർപ്പിക്കൂ',
      'loading': 'ലോഡ് ചെയ്യുന്നു...',
      'error': 'പിശക്',
      'success': 'വിജയം',
      'retry': 'വീണ്ടും ശ്രമിക്കൂ',
      'no_data': 'ഡേറ്റ ഒന്നുമില്ല',
      'choose_language': 'ഭാഷ തിരഞ്ഞെടുക്കൂ',
      'language': 'ഭാഷ',
      'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കൂ',
      'app_language': 'ആപ്പ് ഭാഷ',
      'rupee': '₹',
      'km': 'കി.മീ',
      'mins': 'മിനിറ്റ്',
      'enter_destination': 'ലക്ഷ്യസ്ഥാനം നൽകുക',
      'service_area': 'ഹൈദരാബാദ് & ആന്ധ്രാ',
    },
  };
}
